# Generated by Django 4.0.4 on 2022-06-04 06:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reg_org', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartOf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prem', models.CharField(choices=[('em', 'EMPLOYEE'), ('pl', 'PROJECT_LEAD'), ('mr', 'MANAGER')], default='em', max_length=2)),
                ('emp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('org', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reg_org.organization')),
            ],
        ),
        migrations.CreateModel(
            name='IsRoot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_root', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
