# Generated by Django 4.0.4 on 2022-06-05 06:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('reg_org', '0002_partof_isroot'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='client_secret',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
