# Generated by Django 4.0.4 on 2022-06-13 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reg_org', '0003_organization_client_secret'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partof',
            name='prem',
        ),
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_name', models.CharField(max_length=100)),
                ('org', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reg_org.organization')),
            ],
        ),
    ]
